Creates events and user_events join table
danman01/wise_coders_app pull request #5
Opened 2019-02-16 19:03 UTC by Natesuri

Used rails scaffolding for table creation
Establishes Many to Many between User and Event

Advances #1

2019-02-18 21:44 UTC, danman01 requested changes

2019-02-18 21:44 UTC, danman01 commented on db/schema.rb
> +    t.date "start_date"
Let's use `datetime` for this so we can capture the full timestamp

2019-02-18 21:44 UTC, danman01 commented on app/controllers/user_events_controller.rb
> +      params.require(:user_event).permit(:user_id, :events_id, :quantity, :working_on, :share_tech, :teach_tech)
I think this is supposed to be `event_id`, which will be the incoming param from the client that'll map to the `event_id` attribute of a new `UserEvent`

2019-02-19 20:45 UTC, Natesuri commented
Hey Danny,

I've made the changes you've requested.

2019-02-22 01:58 UTC, danman01 approved these changes

2019-02-22 01:59 UTC, merged